spring.application.name=sistematickets

# Configuración URL de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_tickets_db

# Configuración nombre de usuario y contraseña de la BD
spring.datasource.username=root
spring.datasource.password=root

# Configuración para creación y actualización automática de tablas en la base de datos
spring.jpa.hibernate.ddl-auto=update

# Configuración para mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Configuración para formatear las consultas SQL en la consola
spring.jpa.properties.hibernate.format_sql=true

# Le dice a hibernate que use el dialecto de MySQL
spring.jpa.database.platform=org.hibernate.dialect.MySQLDialect

